### ISSUE TITLE
 getUrlParams is not defined

### ISSUE THREAD

**Issue by renhao233** [chikara-chen/react-isomorphic#2]
### 运行环境
OSX(10.12)
node(v6.9.4)
npm(3.10.10)
### 错误截图
```shell
[nodemon] starting `node ./server/server.dev.js`
/Users/****/Workspace/react-isomorphic-boilerplate/client/shared/utils.js:61
    getUrlParams: getUrlParams
                  ^

ReferenceError: getUrlParams is not defined
    at Object.<anonymous> (/Users/****/Workspace/react-isomorphic-boilerplate/client/shared/utils.js:51:5)
    at Module._compile (module.js:570:32)
    at loader (/Users/****/Workspace/react-isomorphic-boilerplate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/****/Workspace/react-isomorphic-boilerplate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/****)/Workspace/react-isomorphic-boilerplate/client/common/actions/index.js:2:1)
    at Module._compile (module.js:570:32)
    at loader (/Users/****/Workspace/react-isomorphic-boilerplate/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/****/Workspace/react-isomorphic-boilerplate/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
### 代码截图
```javascript
function getURLParams() {
    const search = location.search.slice(1),
        rParam = /([^&]*)=([^&]*)/g
    let ret = {},
        param

    while (param = rParam.exec(search)) {
        ret[param[1]] = param[2]
    }

    return ret
}

export default {
    ajax,
    getURLParams
}
```
> getURLParams原本为getUrlParams，修改为getURLParams后可以成功运行。

**Comment by chikara-chan** [comment]
Has fixed and merged lately at master branch.
